var tweets = [{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/28485132\/Tim_normal.png",
    "description": "Web geek with a camera.",
    "screen_name": "timbray",
    "url": "http:\/\/www.tbray.org\/ongoing\/",
    "name": "Tim Bray",
    "protected": false,
    "followers_count": 3491,
    "location": "Vancouver, Canada",
    "id": 1235521
  },
  "created_at": "Mon Nov 10 02:38:24 +0000 2008",
  "in_reply_to_user_id": 790205,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": 998079351,
  "id": 998205969,
  "source": "<a href=\"http:\/\/iconfactory.com\/software\/twitterrific\">twitterrific<\/a>",
  "text": "@chadfowler The further in you go, the bigger it gets."
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/59628946\/avitar_normal.jpg",
    "description": "songwriter",
    "screen_name": "derrekwayne",
    "url": "http:\/\/derrekwayne.com",
    "name": "Derrek Wayne",
    "protected": false,
    "followers_count": 105,
    "location": "Portland Oregon",
    "id": 13502072
  },
  "created_at": "Mon Nov 10 02:34:01 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998201790,
  "source": "web",
  "text": "Circuit bent Sega : http:\/\/vimeo.com\/123315"
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/27004932\/right_looking_evilgrin_normal.jpg",
    "description": "",
    "screen_name": "gnat",
    "url": "http:\/\/nathan.torkington.com\/",
    "name": "Nat Torkington",
    "protected": false,
    "followers_count": 1409,
    "location": "New Zealand",
    "id": 898691
  },
  "created_at": "Mon Nov 10 02:32:10 +0000 2008",
  "in_reply_to_user_id": 14849737,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": 998195122,
  "id": 998199886,
  "source": "<a href=\"http:\/\/www.twhirl.org\/\">twhirl<\/a>",
  "text": "@davetenhave Do you know what's ACT's policy is on environment\/global warming? Can't find it on http:\/\/www.act.org.nz\/policies"
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/52708679\/craig.obama.2_normal.jpg",
    "description": "customer service rep &amp; founder for craigslist",
    "screen_name": "craignewmark",
    "url": "http:\/\/cnewmark.com",
    "name": "craignewmark",
    "protected": false,
    "followers_count": 4112,
    "location": "iPhone: 37.800186,-122.379730",
    "id": 14368074
  },
  "created_at": "Mon Nov 10 02:25:33 +0000 2008",
  "in_reply_to_user_id": 12193342,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": 998177160,
  "id": 998193033,
  "source": "<a href=\"http:\/\/itweet.net\/\">iTweet<\/a>",
  "text": "@rachelsklar You were good on CNN yesterday, also looked really good!"
},
{
  "in_reply_to_status_id": 997931230,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/52708679\/craig.obama.2_normal.jpg",
    "description": "customer service rep &amp; founder for craigslist",
    "screen_name": "craignewmark",
    "url": "http:\/\/cnewmark.com",
    "name": "craignewmark",
    "protected": false,
    "followers_count": 4112,
    "location": "iPhone: 37.800186,-122.379730",
    "id": 14368074
  },
  "favorited": false,
  "created_at": "Mon Nov 10 02:25:02 +0000 2008",
  "in_reply_to_user_id": 14415152,
  "truncated": false,
  "id": 998192501,
  "source": "<a href=\"http:\/\/itweet.net\/\">iTweet<\/a>",
  "text": "@kristyann You're right! My response reflects my sense of humor and a headache all day."
},
{
  "in_reply_to_user_id": 43833,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/58792859\/Kavatar_normal.jpg",
    "description": "Reading your thoughts. if you write them first.",
    "screen_name": "kevinmarks",
    "followers_count": 3011,
    "url": "http:\/\/epeus.blogspot.com",
    "name": "Kevin Marks",
    "protected": false,
    "location": "San Jose",
    "id": 57203
  },
  "truncated": false,
  "created_at": "Mon Nov 10 02:21:09 +0000 2008",
  "favorited": false,
  "in_reply_to_status_id": 998171922,
  "id": 998188606,
  "source": "<a href=\"http:\/\/twitterhelp.blogspot.com\/2008\/05\/twitter-via-mobile-web-mtwittercom.html\">mobile web<\/a>",
  "text": "@dantekgeek can't you use 'each' instead of 'both' for more than 2 (conversely, try 'all')"
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/60754198\/Buddy_Picture_normal.jpg",
    "description": "",
    "screen_name": "allisbe",
    "url": null,
    "name": "Allison",
    "protected": false,
    "followers_count": 142,
    "location": "Portland, OR",
    "id": 10096
  },
  "created_at": "Mon Nov 10 02:20:41 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998188107,
  "source": "web",
  "text": "linus strikes the statue pose directly under the drafting table lamp... as if on stage, commanding the audience to pay attention."
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/60484773\/hmmmm_normal.jpg",
    "description": "",
    "screen_name": "willcodeforfoo",
    "url": null,
    "name": "Kevin",
    "protected": false,
    "followers_count": 144,
    "location": "Toledo, Ohio",
    "id": 56813
  },
  "created_at": "Mon Nov 10 02:18:22 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998185708,
  "source": "web",
  "text": "Tonight's Family Guy is rather funny... liked the 9 minute Snooze button gag"
},
{
  "in_reply_to_status_id": 998175762,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/56879528\/2680334931_0c392dd9a7_s_normal.jpg",
    "description": "Writer, photographer, programmer, geek",
    "screen_name": "spinnerin",
    "url": "http:\/\/lifeofaudrey.com",
    "name": "Audrey",
    "protected": false,
    "followers_count": 583,
    "location": "Laurelhurst, Oregon",
    "id": 49333
  },
  "favorited": false,
  "created_at": "Mon Nov 10 02:14:58 +0000 2008",
  "in_reply_to_user_id": 15249705,
  "truncated": false,
  "id": 998182213,
  "source": "<a href=\"http:\/\/iconfactory.com\/software\/twitterrific\">twitterrific<\/a>",
  "text": "@lizzycaston Charcuterie class sounds interesting. Send me info?"
},
{
  "in_reply_to_user_id": null,
  "truncated": false,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/63641499\/2769302491_6586c82d2e_normal.jpg",
    "description": "Developer.. Atheist... and Musician ",
    "screen_name": "robbyrussell",
    "url": "http:\/\/www.robbyrussell.com\/",
    "name": "Robby Russell",
    "protected": false,
    "followers_count": 510,
    "location": "Portland, Oregon",
    "id": 54793
  },
  "in_reply_to_status_id": null,
  "created_at": "Mon Nov 10 02:12:56 +0000 2008",
  "favorited": false,
  "id": 998180336,
  "source": "<a href=\"http:\/\/iconfactory.com\/software\/twitterrific\">twitterrific<\/a>",
  "text": "NW Portland graffiti http:\/\/twitpic.com\/kz6h"
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/63326968\/barackobama_bigger_normal.jpg",
    "description": "Grabb.it (music + web programming), art, physical computing",
    "screen_name": "atduskgreg",
    "url": "http:\/\/www.urbanhonking.com\/ideasfordozens",
    "name": "Greg",
    "protected": false,
    "followers_count": 313,
    "location": "Portland, OR",
    "id": 26853
  },
  "created_at": "Mon Nov 10 02:09:01 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998176420,
  "source": "<a href=\"http:\/\/help.twitter.com\/index.php?pg=kb.page&id=75\">txt<\/a>",
  "text": "landed at laguardia. never seen a cab line like this before"
},
{
  "in_reply_to_status_id": 998168290,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/61379092\/nfavatar_normal.jpg",
    "description": "making my way the only way i know how",
    "screen_name": "natdefreitas",
    "url": "http:\/\/openideals.com",
    "name": "Nathan Freitas",
    "protected": false,
    "followers_count": 504,
    "location": "brooklyn, ny",
    "id": 13527
  },
  "favorited": false,
  "created_at": "Mon Nov 10 02:07:19 +0000 2008",
  "in_reply_to_user_id": 4848301,
  "truncated": false,
  "id": 998174668,
  "source": "web",
  "text": "@davetroy so cool! (re: http:\/\/votereport.us\/TimeView\/applet\/).... reminds me of that global airline flight visualization"
},
{
  "in_reply_to_status_id": null,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/52941014\/headshot-2008-04-16-01_normal.jpg",
    "description": "Rubyist since 2001. Syntax Herder, Bezier Curve Wrangler.",
    "screen_name": "wbruce",
    "url": "http:\/\/codefluency.com",
    "name": "Bruce Williams",
    "protected": false,
    "followers_count": 639,
    "location": "Austin, TX",
    "id": 38353
  },
  "favorited": false,
  "created_at": "Mon Nov 10 02:04:00 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "id": 998170955,
  "source": "web",
  "text": "Back in Austin. SO happy to be home, and no plans to leave again until March!"
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/63073644\/Wearing_my_special_massage_outfit_on_Flickr_-_Photo_Sharing__normal.jpg",
    "description": "CEO of Twitter",
    "screen_name": "ev",
    "url": "http:\/\/evhead.com",
    "name": "Evan Williams",
    "protected": false,
    "followers_count": 22034,
    "location": "San Francisco, CA, US",
    "id": 20
  },
  "in_reply_to_user_id": null,
  "created_at": "Mon Nov 10 02:03:47 +0000 2008",
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998170714,
  "source": "<a href=\"http:\/\/help.twitter.com\/index.php?pg=kb.page&id=75\">txt<\/a>",
  "text": "Great wknd. Super-relaxed."
},
{
  "user": {
    "description": "If it ain't broke... break it.",
    "url": "http:\/\/philcrissman.com",
    "name": "Phil Crissman",
    "protected": false,
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/61980624\/Photo_10_normal.jpg",
    "location": "Minneapolis",
    "id": 7669762,
    "followers_count": 1180,
    "screen_name": "philcrissman"
  },
  "created_at": "Mon Nov 10 01:58:33 +0000 2008",
  "in_reply_to_status_id": null,
  "in_reply_to_user_id": null,
  "truncated": false,
  "id": 998165258,
  "favorited": false,
  "source": "web",
  "text": "I have lots of work to do. Instead, I am writing applications in Shoes (http:\/\/shoooes.net)."
},
{
  "in_reply_to_user_id": null,
  "user": {
    "description": "I like my blogging like my beer: bitter and cold.",
    "followers_count": 145,
    "url": "http:\/\/rcoder.net\/",
    "name": "Lennon Day-Reynolds",
    "protected": false,
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/55578228\/hair_sm_normal.jpg",
    "location": "Portland, OR",
    "id": 4930131,
    "screen_name": "rcoder"
  },
  "truncated": false,
  "created_at": "Mon Nov 10 01:58:04 +0000 2008",
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998164795,
  "source": "<a href=\"http:\/\/twidroid.com\">twidroid<\/a>",
  "text": "Baking acorn squash and getting the grill fired up. Extreme slack continues apace."
},
{
  "in_reply_to_user_id": null,
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/63488490\/img_1356__Modified_in_GIMP_Image_Editor__normal.jpg",
    "description": "hacker, biker, dreamer",
    "screen_name": "donpdonp",
    "followers_count": 456,
    "url": "http:\/\/donpark.org",
    "name": "Don Park",
    "protected": false,
    "location": "Portland, Or",
    "id": 608093
  },
  "truncated": false,
  "created_at": "Mon Nov 10 01:58:04 +0000 2008",
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998164790,
  "source": "web",
  "text": "my picowrimo story is all narrative. inventing dialogue has been near impossible so far."
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/56299885\/2007_05_00382_vectorized_normal.png",
    "description": "Software Engineer",
    "screen_name": "jwilger",
    "url": "http:\/\/johnwilger.com",
    "name": "John Wilger",
    "protected": false,
    "followers_count": 111,
    "location": "Witch Hazel, Oregon",
    "id": 7299852
  },
  "in_reply_to_user_id": null,
  "created_at": "Mon Nov 10 01:51:50 +0000 2008",
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998158453,
  "source": "<a href=\"http:\/\/twitterhelp.blogspot.com\/2008\/05\/twitter-via-mobile-web-mtwittercom.html\">mobile web<\/a>",
  "text": "DAMNIT! Beer tastes really good but is almost completely flat. I knew I should have added some healthy yeast before bottling."
},
{
  "user": {
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/63846355\/mattly_pic.jpg_normal.jpg",
    "description": "i am mister edge-case",
    "screen_name": "mattly",
    "url": "http:\/\/mattly.tumblr.com\/",
    "name": "matthew lyon",
    "protected": false,
    "followers_count": 230,
    "location": "",
    "id": 1768041
  },
  "created_at": "Mon Nov 10 01:50:26 +0000 2008",
  "in_reply_to_user_id": null,
  "truncated": false,
  "favorited": false,
  "in_reply_to_status_id": null,
  "id": 998156952,
  "source": "<a href=\"http:\/\/iconfactory.com\/software\/twitterrific\">twitterrific<\/a>",
  "text": "picked up @ameratsu from @allynmejia and now she doesn't seem to know me anymore."
},
{
  "favorited": false,
  "user": {
    "followers_count": 619,
    "profile_image_url": "http:\/\/s3.amazonaws.com\/twitter_production\/profile_images\/55950951\/pipe_normal.jpg",
    "description": "SE PDXer, Witing about Portland at PDXPipeline.com, Myspace.com\/PdxPipeline",
    "screen_name": "PdxPipeline",
    "url": "http:\/\/pdxpipeline.com",
    "name": "PDX Pipeline",
    "protected": false,
    "location": "portland, oregon",
    "id": 2797681
  },
  "created_at": "Mon Nov 10 01:49:10 +0000 2008",
  "in_reply_to_user_id": 15433919,
  "in_reply_to_status_id": 998153184,
  "truncated": false,
  "id": 998155649,
  "source": "<a href=\"http:\/\/www.tweetdeck.com\/\">TweetDeck<\/a>",
  "text": "@stevenwalling Congratulations on the NYTimes mention!"
}]